#!/bin/bash
#restart docker if 5** status resieved from backend host
#touch reloadlog.log
#chmod 0777 reloadlog.lo

URL="https://admin.kupitrip.online/admin/login"
SCRIPT_DIR=$(dirname "$0")
LOG_FILE="$SCRIPT_DIR/reloadlog.log"

log_status() {
    local status=$1
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $status" >> "$LOG_FILE"
}


if [ "$1" == "force" ]; then
    docker restart $(docker ps -q)
    log_status "Force restart of all containers."
    exit 0
fi


HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" $URL)

if [ "$HTTP_STATUS" -eq 504 ] || [ "$HTTP_STATUS" -eq 503 ] || [ "$HTTP_STATUS" -eq 502 ] || [ "$HTTP_STATUS" -eq 501 ] || [ "$HTTP_STATUS" -eq 500 ]; then
    docker restart $(docker ps -q)
    log_status "Containers restarted due to HTTP status $HTTP_STATUS."
else
    log_status "HTTP status $HTTP_STATUS - no action taken."
fi
